#ifndef _H_CIRCULAR_BUFFER_ERROR_CODES_STR_
#define _H_CIRCULAR_BUFFER_ERROR_CODES_STR_

#include "circular_buffer_export.h"

#ifdef __cplusplus
extern "C"
{
#endif /* __cplusplus */

#define CBUF_INVALID_BUF_PARAMS_STR         ERROR_STRING(CBUF_INVALID_BUF_PARAMS)
#define CBUF_INVALID_DATA_PARAMS_STR        ERROR_STRING(CBUF_INVALID_DATA_PARAMS)
#define CBUF_INVALID_CBUF_HDL_STR           ERROR_STRING(CBUF_INVALID_CBUF_HDL)
#define CBUF_NO_FREE_BUFFERS_STR            ERROR_STRING(CBUF_NO_FREE_BUFFERS)
#define CBUF_NOT_ENUF_SPACE_STR             ERROR_STRING(CBUF_NOT_ENUF_SPACE)
#define CBUF_INVALID_BUFFER_ADDR_STR        ERROR_STRING(CBUF_INVALID_BUFFER_ADDR)
#define CBUF_INVALID_FUNC_PARAMS_STR        ERROR_STRING(CBUF_INVALID_FUNC_PARAMS)

#define CIRCULAR_BUFFER_ERROR_CODES \
    {CBUF_INVALID_BUF_PARAMS, CBUF_INVALID_BUF_PARAMS_STR},\
    {CBUF_INVALID_DATA_PARAMS, CBUF_INVALID_DATA_PARAMS_STR},\
    {CBUF_INVALID_CBUF_HDL, CBUF_INVALID_CBUF_HDL_STR},\
    {CBUF_NO_FREE_BUFFERS, CBUF_NO_FREE_BUFFERS_STR},\
    {CBUF_NOT_ENUF_SPACE, CBUF_NOT_ENUF_SPACE_STR},\
    {CBUF_INVALID_BUFFER_ADDR, CBUF_INVALID_BUFFER_ADDR_STR},\
    {CBUF_INVALID_FUNC_PARAMS, CBUF_INVALID_FUNC_PARAMS_STR},\

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _H_CIRCULAR_BUFFER_ERROR_CODES_STR_ */