#ifndef _H_CIRCULAR_BUFFER_MT_ERROR_CODES_STR_
#define _H_CIRCULAR_BUFFER_MT_ERROR_CODES_STR_

#include "circular_buffer_mt_export.h"

#ifdef __cplusplus
extern "C"
{
#endif /* __cplusplus */

#define CBUF_MT_INVALID_FUNC_PARAMS_STR     ERROR_STRING(CBUF_MT_INVALID_FUNC_PARAMS)
#define CBUF_MT_INVALID_BUF_PARAMS_STR      ERROR_STRING(CBUF_MT_INVALID_BUF_PARAMS)
#define CBUF_MT_INVALID_INPUT_BUF_PARAMS_STR ERROR_STRING(CBUF_MT_INVALID_INPUT_BUF_PARAMS)
#define CBUF_MT_INVALID_OUTPUT_BUF_PARAMS_STR ERROR_STRING(CBUF_MT_INVALID_OUTPUT_BUF_PARAMS)
#define CBUF_MT_INVALID_HDL_STR             ERROR_STRING(CBUF_MT_INVALID_HDL)
#define CBUF_MT_INVALID_FLAGS_STR           ERROR_STRING(CBUF_MT_INVALID_FLAGS)
#define CBUF_MT_NO_FREE_BUFFERS_STR         ERROR_STRING(CBUF_MT_NO_FREE_BUFFERS)
#define CBUF_MT_NOT_ENUF_SPACE_STR          ERROR_STRING(CBUF_MT_NOT_ENUF_SPACE)
#define CBUF_MT_NOT_ENUF_DATA_STR           ERROR_STRING(CBUF_MT_NOT_ENUF_DATA)
#define CBUF_MT_SUSPENDED_WRITE_STR         ERROR_STRING(CBUF_MT_SUSPENDED_WRITE)
#define CBUF_MT_SUSPENDED_READ_STR          ERROR_STRING(CBUF_MT_SUSPENDED_READ)
#define CBUF_MT_MUTEX_INIT_FAILED_STR       ERROR_STRING(CBUF_MT_MUTEX_INIT_FAILED)
#define CBUF_MT_CONDV_INIT_FAILED_STR       ERROR_STRING(CBUF_MT_CONDV_INIT_FAILED)
#define CBUF_MT_MUTEX_DESTROY_FAILED_STR    ERROR_STRING(CBUF_MT_MUTEX_DESTROY_FAILED)
#define CBUF_MT_CONDV_DESTROY_FAILED_STR    ERROR_STRING(CBUF_MT_CONDV_DESTROY_FAILED)
#define CBUF_MT_MUTEX_LOCK_FAILED_STR       ERROR_STRING(CBUF_MT_MUTEX_LOCK_FAILED)
#define CBUF_MT_MUTEX_UNLOCK_FAILED_STR     ERROR_STRING(CBUF_MT_MUTEX_UNLOCK_FAILED)
#define CBUF_MT_CONDV_WAIT_FAILED_STR       ERROR_STRING(CBUF_MT_CONDV_WAIT_FAILED)
#define CBUF_MT_CONDV_SIGNAL_FAILED_STR     ERROR_STRING(CBUF_MT_CONDV_SIGNAL_FAILED)

#define CIRCULAR_BUFFER_MT_ERROR_CODES \
    {CBUF_MT_INVALID_FUNC_PARAMS, CBUF_MT_INVALID_FUNC_PARAMS_STR},\
    {CBUF_MT_INVALID_BUF_PARAMS, CBUF_MT_INVALID_BUF_PARAMS_STR},\
    {CBUF_MT_INVALID_INPUT_BUF_PARAMS, CBUF_MT_INVALID_INPUT_BUF_PARAMS_STR},\
    {CBUF_MT_INVALID_OUTPUT_BUF_PARAMS, CBUF_MT_INVALID_OUTPUT_BUF_PARAMS_STR},\
    {CBUF_MT_INVALID_HDL, CBUF_MT_INVALID_HDL_STR},\
    {CBUF_MT_INVALID_FLAGS, CBUF_MT_INVALID_FLAGS_STR},\
    {CBUF_MT_NO_FREE_BUFFERS, CBUF_MT_NO_FREE_BUFFERS_STR},\
    {CBUF_MT_NOT_ENUF_SPACE, CBUF_MT_NOT_ENUF_SPACE_STR},\
    {CBUF_MT_NOT_ENUF_DATA, CBUF_MT_NOT_ENUF_DATA_STR},\
    {CBUF_MT_SUSPENDED_WRITE, CBUF_MT_SUSPENDED_WRITE_STR},\
    {CBUF_MT_SUSPENDED_READ, CBUF_MT_SUSPENDED_READ_STR},\
    {CBUF_MT_MUTEX_INIT_FAILED, CBUF_MT_MUTEX_INIT_FAILED_STR},\
    {CBUF_MT_CONDV_INIT_FAILED, CBUF_MT_CONDV_INIT_FAILED_STR},\
    {CBUF_MT_MUTEX_DESTROY_FAILED, CBUF_MT_MUTEX_DESTROY_FAILED_STR},\
    {CBUF_MT_CONDV_DESTROY_FAILED, CBUF_MT_CONDV_DESTROY_FAILED_STR},\
    {CBUF_MT_MUTEX_LOCK_FAILED, CBUF_MT_MUTEX_LOCK_FAILED_STR},\
    {CBUF_MT_MUTEX_UNLOCK_FAILED, CBUF_MT_MUTEX_UNLOCK_FAILED_STR},\
    {CBUF_MT_CONDV_WAIT_FAILED, CBUF_MT_CONDV_WAIT_FAILED_STR},\
    {CBUF_MT_CONDV_SIGNAL_FAILED, CBUF_MT_CONDV_SIGNAL_FAILED_STR},\

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _H_CIRCULAR_BUFFER_MT_ERROR_CODES_STR_ */