#ifndef _H_CIRCULAR_QUEUE_ERROR_CODES_STR_
#define _H_CIRCULAR_QUEUE_ERROR_CODES_STR_

#include "circular_queue_export.h"

#ifdef __cplusplus
extern "C"
{
#endif /* __cplusplus */

#define CQUE_INVALID_QUEUE_PARAMS_STR       ERROR_STRING(CQUE_INVALID_QUEUE_PARAMS)
#define CQUE_INVALID_DATA_PARAMS_STR        ERROR_STRING(CQUE_INVALID_DATA_PARAMS)
#define CQUE_INVALID_CQUE_HDL_STR           ERROR_STRING(CQUE_INVALID_CQUE_HDL)
#define CQUE_NO_FREE_QUEUES_STR             ERROR_STRING(CQUE_NO_FREE_QUEUES)
#define CQUE_NOT_ENUF_SPACE_STR             ERROR_STRING(CQUE_NOT_ENUF_SPACE)
#define CQUE_INVALID_QUEUE_ADDR_STR         ERROR_STRING(CQUE_INVALID_QUEUE_ADDR)
#define CQUE_INVALID_FUNC_PARAMS_STR        ERROR_STRING(CQUE_INVALID_FUNC_PARAMS)

#define CIRCULAR_QUEUE_ERROR_CODES \
    {CQUE_INVALID_QUEUE_PARAMS, CQUE_INVALID_QUEUE_PARAMS_STR},\
    {CQUE_INVALID_DATA_PARAMS, CQUE_INVALID_DATA_PARAMS_STR},\
    {CQUE_INVALID_CQUE_HDL, CQUE_INVALID_CQUE_HDL_STR},\
    {CQUE_NO_FREE_QUEUES, CQUE_NO_FREE_QUEUES_STR},\
    {CQUE_NOT_ENUF_SPACE, CQUE_NOT_ENUF_SPACE_STR},\
    {CQUE_INVALID_QUEUE_ADDR, CQUE_INVALID_QUEUE_ADDR_STR},\
    {CQUE_INVALID_FUNC_PARAMS, CQUE_INVALID_FUNC_PARAMS_STR},\

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _H_CIRCULAR_QUEUE_ERROR_CODES_STR_ */